version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          command: |
           apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6 git wget gcc clang libssl-dev rsync flex bison cpio libncurses5 curl python-is-python3
           git config --global user.name "ernesto	"
           git config --global user.email "eescodm-gmbh.com"
           git config --global color.ui false
           git clone https://github.com/ernesto-es/scripts2 && cd scripts && bash setup/android_build_env.sh && cd ..
           mkdir predator
           cd predator
           wget https://github.com/ernesto-es/AndroidFirmware/blob/kernel_s21_5g/build_menu
           source build_menu
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
